@startuml
'https://plantuml.com/sequence-diagram

javafx.Application<|-- Controller
Controller -- Inventory
Controller - Item
Controller -- FileManager
Inventory -- FileManager
Inventory *-- Item
App-Controller

Class App{
    start()
}

Class Controller {
     textArea : TextArea
     resultField : TextField
     addValue : TextField
     addSerial : TextField
     addName : TextField
     searchInfo : TextField
     editSerial : TextField
     editName : TextField
     editValue : TextField
     inventory : inventory
     editIndex : int
     fileChooser : FileChooser
     extensionSet : boolean

     addItem()
     searchByName()
     searchBySerialNumber()
     editItem()
     deleteItem()
     sortByName()
     sortBySerial()
     sortbyValue()
     saveFile()
     loadFile()
}

Class FileManager{
     data : String

     setData()
     readData()
     readTSV()
     readHTML()
     readJSON()
     saveData()
     formatTSV()
     formatJSON()
     formatHTML()
}

Class Inventory{
     itemList : ArrayList<Item>

     addItem()
     getItems()
     getItemIndexByName()
     displayInfo()
     confirmSerialUniqueness()
     sortByValue()
     sortBySerialNumber()
     sortByName()
     confirmOnlyOne()
}

Class Item{
     value : double
     serialNumber : String
     name : String
     valueString : String

     Item()
     setValue()
     getValue
     setSerialNumber()
     getSerialNumber()
     setName()
     getName()
     itemConstructor()
     confirmSerialFormat()
     confirmNameLength()
}
@enduml